### ISSUE TITLE
solver qui s'arrete

### ISSUE THREAD

**Issue by Rex7391** [Lgt2x/Rubik-s-Cube-Java#31]
si on clique sur mélanger puis résoudre : 
tout clic sur le bouton finir va entraîner une impossibilité pour le solveur de résoudre le cube après (idem avec les fleches ) !

**Comment by Lgt2x** [comment]
@Rex7391 j'arrive pas à reproduire le problème, t'es sûr que tu jouais avec la dernière version ? Ferme l'issue si ça marche
